name: CI/CD - Spring Boot com Docker

on:
  push:
    branches:
      - develop
      - main

jobs:
  build-ngrok:
    runs-on: ubuntu-latest
    steps:
      - name: Expor aplicação com ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
          nohup ngrok http 8080 > /dev/null 2>&1 &

      - name: Exibir URL pública do ngrok
        run: curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'

      - name: Salvar logs da aplicação
        run: docker logs cicd-container > logs.txt

      - name: Upload logs como artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-logs
          path: logs.txt

      - name: Testar aplicação rodando no container
        run: |
          sleep 10
          curl -I http://localhost:8080